(() => {
  'use strict';
  window.CFPR=window.CFPR||{};
  CFPR.CONSTANTS=Object.freeze({DEFAULT_RATING:1400,MIN_RATING:-500,MAX_RATING:6000,REFRESH_MS:90000,STANDINGS_CACHE_MS:15000,RATING_CACHE_DAYS:7,CONTEST_RATING_CACHE_KEY:'cfprContestRatings',SETTINGS_KEY:'cfprSettings',VIRTUAL_SUBMISSION_CACHE_MS:10000,VERSION:'4.0.0'});
})();