(() => {
'use strict';
const S={id:null,title:'',username:null,phase:'',rows:[],predictions:new Map(),lastUpdated:0,busy:false,timer:null,virtual:false};
const PANEL='cfpr-panel',DELTA='cfpr-delta',NEW='cfpr-new',PERF='cfpr-perf';
const esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=x=>x>0?'+'+x:String(x);
function user(){const a=document.querySelector('a[href="/profile/"]');if(a)return a.textContent.trim();const links=[...document.querySelectorAll('a[href*="/profile/"]')];const me=links.find(a=>a.classList.contains('rated-user')||a.classList.contains('user-black')||a.classList.contains('my-contest'));return me?.textContent.trim()||document.querySelector('#header a[href*="/profile/"]')?.textContent.trim()||null}
function title(){return document.querySelector('.contest-title')?.textContent.trim()||document.querySelector('div[style*="text-align: center"] h1')?.textContent.trim()||document.title.replace(/ - Codeforces$/,'').trim()}
function rowsFromStandings(x){return (x.rows||[]).map(r=>{const p=r.party||{};const h=p.members?.[0]?.handle;return h?{handle:h,rank:Number(r.rank),points:Number(r.points)||0,penalty:Number(r.penalty)||0,rating:null}:null}).filter(Boolean)}
function pageRows(){return CFPR.DOM.getTableRows().map((tr,i)=>{const h=CFPR.DOM.extractHandle(tr);if(!h)return null;const cells=[...tr.querySelectorAll('td')];let rank=Number((cells[0]?.textContent||'').match(/^\s*(\d+)/)?.[1])||i+1;return{handle:h,rank,points:0,penalty:0,rating:null}}).filter(Boolean)}
function findMe(){const u=user();if(u)return u;return [...document.querySelectorAll('a[href*="/profile/"]')].find(a=>a.textContent.trim()&&a.closest('tr')?.classList.contains('highlighted'))?.textContent.trim()||null}
function panel(){let p=document.getElementById(PANEL);if(p)return p;p=document.createElement('div');p.id=PANEL;p.innerHTML='<div class="cfpr-panel-top"><div class="cfpr-brand"><span class="cfpr-logo-dot"></span><div><div class="cfpr-title">CF Rating Predictor</div><div class="cfpr-subtitle"></div></div></div><span class="cfpr-status-pill"></span></div><div class="cfpr-panel-main"><div class="cfpr-stat"><span class="cfpr-stat-label">You</span><span class="cfpr-stat-value" id="cfpr-you">—</span></div><div class="cfpr-stat"><span class="cfpr-stat-label">Δ</span><span class="cfpr-stat-value" id="cfpr-delta">—</span></div><div class="cfpr-stat"><span class="cfpr-stat-label">New rating</span><span class="cfpr-stat-value" id="cfpr-new">—</span></div><div class="cfpr-stat"><span class="cfpr-stat-label">Rank</span><span class="cfpr-stat-value" id="cfpr-rank">—</span></div><button class="cfpr-action" id="cfpr-refresh">Refresh</button></div><div class="cfpr-meta" id="cfpr-meta"></div>';const t=CFPR.DOM.getTable();if(t)t.parentNode.insertBefore(p,t);return p}
function setPanel(text,status=''){const p=panel();p.querySelector('.cfpr-subtitle').textContent=S.title||('Contest '+S.id);p.querySelector('.cfpr-status-pill').textContent=status||S.phase||'READY';p.querySelector('.cfpr-status-pill').className='cfpr-status-pill '+(status==='LIVE'?'live':status==='FINISHED'?'final':'');p.querySelector('#cfpr-you').textContent=S.username||'Not detected';p.querySelector('#cfpr-meta').textContent=text}
function headerCell(id,text){const th=document.createElement('th');th.id=id;th.className='cfpr-head cfpr-pred-col';th.textContent=text;th.title=text;th.rowSpan=2;return th}
function ensureHeaders(){const h=CFPR.DOM.getHeaderRow();if(!h)return;const who=CFPR.DOM.findWhoColumnIndex();const target=h.children[who];if(!target)return;[[DELTA,'Pred Δ'],[NEW,'New Rating'],[PERF,'Performance']].forEach(([id,txt])=>{if(!document.getElementById(id)){const th=headerCell(id,txt);target.insertAdjacentElement('afterend',th)}})}
function clearCells(){CFPR.DOM.getTable()?.querySelectorAll('.cfpr-pred-col[data-cfpr-cell]').forEach(x=>x.remove())}
function cell(text,cls=''){const td=document.createElement('td');td.className='cfpr-pred-col '+cls;td.dataset.cfprCell='1';td.textContent=text;return td}
function render(){ensureHeaders();clearCells();const rows=CFPR.DOM.getTableRows();for(const tr of rows){const h=CFPR.DOM.extractHandle(tr),p=S.predictions.get(h);if(!p)continue;const d=p.delta,n=p.rating!=null&&d!=null?p.rating+d:null;const who=CFPR.DOM.findWhoCell(tr);if(!who)continue;who.insertAdjacentElement('afterend',cell(d==null?'—':fmt(d),d>0?'cfpr-up':d<0?'cfpr-down':'cfpr-neutral'));who.nextElementSibling.insertAdjacentElement('afterend',cell(n==null?'—':String(n),d>0?'cfpr-up':d<0?'cfpr-down':'cfpr-neutral'));if(S.settings?.showPerformance!==false)who.nextElementSibling.nextElementSibling.insertAdjacentElement('afterend',cell(p.performance==null?'—':String(p.performance),'cfpr-perf'));if(h===S.username)tr.classList.add('cfpr-me')}
const me=S.predictions.get(S.username);if(me){document.getElementById('cfpr-delta').textContent=me.delta==null?'—':fmt(me.delta);document.getElementById('cfpr-new').textContent=me.rating==null||me.delta==null?'—':String(me.rating+me.delta);document.getElementById('cfpr-rank').textContent=me.rank??'—'}setPanel(S.virtual?'Virtual prediction updated':'Prediction updated',S.virtual?'VIRTUAL':S.phase)}
async function refresh(force=false){if(S.busy||!S.id)return;S.busy=true;try{S.id=CFPR.DOM.getContestId();S.username=findMe();S.virtual=CFPR.DOM.isVirtualParticipationPage()||/\/virtual\/?$/i.test(location.pathname);const st=await CFPR.API.getContestStandings(S.id,{force});S.title=st.contest?.name||title();S.phase=st.contest?.phase||(/running/i.test(document.body.innerText)?'LIVE':'FINISHED');let rows=rowsFromStandings(st);if(!rows.length)rows=pageRows();const handles=rows.map(r=>r.handle);const ratings=await CFPR.API.getContestRatings(S.id,handles);for(const r of rows)r.rating=ratings.get(r.handle);S.rows=rows;
if(S.phase==='FINISHED'&&!S.virtual){const changes=await CFPR.API.getRatingChanges(S.id);S.predictions=new Map(changes.map(x=>[x.handle,{handle:x.handle,rank:x.rank,delta:Number(x.ratingUpdate)||0,rating:Number(x.oldRating)}]));}
else {const field=rows.filter(r=>r.rating!=null);const pred=CFPR.Rating.predict(field,true);S.predictions=new Map(pred.map(p=>[p.handle,p]));if(S.virtual&&S.username&&!S.predictions.has(S.username)){const me=pageRows().find(x=>x.handle===S.username);if(me){const base=field.filter(x=>x.handle!==S.username);base.push({...me,rating:ratings.get(S.username)});const pp=CFPR.Rating.predict(base,true).find(x=>x.handle===S.username);if(pp)S.predictions.set(S.username,pp)}}}
S.lastUpdated=Date.now();render()}catch(e){setPanel('Unable to update: '+(e?.message||'unknown error'),'ERROR')}finally{S.busy=false}}
function start(){S.id=CFPR.DOM.getContestId();if(!S.id)return;S.username=findMe();S.settings={showPerformance:true};panel();document.getElementById('cfpr-refresh').onclick=()=>refresh(true);chrome.storage.local.get(CFPR.CONSTANTS.SETTINGS_KEY,d=>{S.settings={showPerformance:true,...(d[CFPR.CONSTANTS.SETTINGS_KEY]||{})};render()});refresh(false);clearInterval(S.timer);S.timer=setInterval(()=>refresh(false),CFPR.CONSTANTS.REFRESH_MS)}
chrome.runtime.onMessage.addListener((m,s,send)=>{if(m.type==='CFPR_REFRESH'){refresh(true).finally(()=>send({ok:true}));return true}if(m.type==='CFPR_SETTINGS_UPDATED'){S.settings=m.settings||S.settings;render();send({ok:true});return}if(m.type==='CFPR_GET_STATUS'){send({ok:true,contestId:S.id,phase:S.virtual?'VIRTUAL':S.phase,username:S.username,lastUpdated:S.lastUpdated,predictions:S.predictions.size,busy:S.busy});return}});
let boot=0;const observer=new MutationObserver(()=>{if(!S.id&&CFPR.DOM.getTable()&&boot++<20)start()});observer.observe(document.documentElement,{childList:true,subtree:true});start();
})();